// <auto-generated />
namespace Cookishly.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Database_001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Database_001));
        
        string IMigrationMetadata.Id
        {
            get { return "201503111957508_Database_001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
